app/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('forms.urls', 'forms'), namespace='forms')),
    path('productos/', include(('products.urls', 'products'), namespace='products')),
    path('carrito/', include(('carts.urls', 'carts'), namespace='carts')),
    path('orden/', include(('orders.urls', 'orders'), namespace='orders')),
    path('direcciones/', include(('shipping_addresses.urls', 'shipping_addresses'), namespace='shipping_addresses')),
    path('codigos/', include(('promo_codes.urls', 'promo_codes'), namespace='promo_codes')),
    path('pagos/', include(('billing_profiles.urls', 'billing_profiles'), namespace='billing_profiles')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
# Django
from django.urls import path

# Views
from . import views

# No es necesario añadir lo siguiente si la las rutas 
# principales tienen un namespace definido para
# cada aplicación. '''
app_name = 'products'

urlpatterns = [
    path('search', views.ProductSearchListView.as_view(), name='search'),
    path('<slug:slug>', views.ProductDetailView.as_view(), name='product_detail'), #id -> llave primaria

]

products/models.py
# Django
from django.db import models
from django.utils.text import slugify

# Signals
from django.db.models.signals import pre_save

# Uttils
import uuid


class Product(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    image = models.ImageField(upload_to='products/', null=False, blank=False)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0.0) #12234.50

    slug = models.SlugField(null=False, blank=False, unique=True)

    created_at = models.DateTimeField(auto_now_add=True)


    # def save(self, *args, **kwargs):
    #     self.slug = slugify(self.title) # 'slugify' genera un slug automático. GRACIAS DJANGO
    #     super(Product, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

def set_slug(sender, instance, *args, **kwargs): #callback
    print('Estoy dentro de la función')
    if instance.title and not instance.slug:
        print('Estoy dentro del if')
        slug = slugify(instance.title)

        while Product.objects.filter(slug=slug).exists():
            print('Estoy dentro del while!')
            slug = slugify(
                '{}-{}'.format(instance.title, str(uuid.uuid4())[:8])
            )

        instance.slug = slug


    print(sender); print(instance)

pre_save.connect(set_slug, sender=Product)

products/views.py
# Django
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.db.models import Q

# Models
from .models import Product


class ProductListView(ListView):
    template_name = 'index.html'
    queryset = Product.objects.all().order_by('-id')


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de productos'
        # context['products'] = context['object_list']
        # print(context)

        return context

class ProductDetailView(DetailView): #id -> pk
    model = Product
    template_name = 'products/product.html'

    def get_context_data(self, **kwargs):
        ''' No aplicamos ningún cambio, sin embargo
        de este modo seremos capaces de imprimir el
        contexto, y así poder conocer su contenido :) '''
        
        context = super().get_context_data(**kwargs)

        # print(context) 
        return context

class ProductSearchListView(ListView):
    template_name = 'products/search.html'

    def query(self):
        '''
        Obtenemos el query ingresado en el formulario.
        '''
        return self.request.GET.get('q')

    def get_queryset(self):
        '''
        Hacemos una búsqueda dinámica, a través del query buscado
        en el formulario, par eso sustituimos el método get_queryset
        '''
        filters = Q(title__icontains=self.query()) | Q(category__title__icontains=self.query())
        return Product.objects.filter(filters)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query()
        context['count'] = context['product_list'].count()

        return context

products/templates/products/snippets/list.html
<div class="row">

    {% for object in object_list %}
        <div class="col-sm-6 col-md-4 col-lg-3 mt-5">
            <!-- Product's Snippets -->
            {% include 'products/snippets/product.html' with product=object %}

        </div>
    {% endfor %}

</div>

products/templates/products/snippets/product.html
<!-- Product -->
<div class="card h-100">

    {% if product.image %}
        <img src="{{ product.image.url }}" alt="Imagen del producto" height="300px">
    {% endif %}

    <div class="card-body">
        <h5 class="card-title"> {{ product.title }} </h5>
        <p class="card-text"> {{ product.description }} </p>
        <a href="{% url 'products:product_detail' product.slug %}" class="btn btn-primary btn-block"> Ver más </a>
    </div>


</div>

products/templates/products/snippets/search.html
<form action="{% url 'products:search' %}">
    <div class="input-group mt-3">

        <input type="text" name="q" class="form-control" placeholder="Buscar" value="{{query}}">

        <div class="input-group-append">
            <input type="submit" value="Buscar" class="btn btn-primary">
        </div>

    </div>
</form>