app/urls.py
# Django
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('forms.urls', 'forms'), namespace='forms')),
    path('productos/', include(('products.urls', 'products'), namespace='products')),
    path('carrito/', include(('carts.urls', 'carts'), namespace='carts')),
    path('orden/', include(('orders.urls', 'orders'), namespace='orders')),
    path('direcciones/', include(('shipping_addresses.urls', 'shipping_addresses'), namespace='shipping_addresses')),
    path('codigos/', include(('promo_codes.urls', 'promo_codes'), namespace='promo_codes')),
    path('pagos/', include(('billing_profiles.urls', 'billing_profiles'), namespace='billing_profiles')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

billing_profiles/urls.py
# Django
from django.urls import path

from . import views

app_name = 'billing_profiles'

urlpatterns = [
    path('', views.BillingProfileListView.as_view(), name='billing_profiles'),
    path('nuevo', views.create, name='create'),
]

carts/urls.py
from django.urls import path

from . import views


app_name = 'carts'


urlpatterns = [
    path('', views.cart, name='cart'),
    path('agregar', views.add, name='add'),
    path('eliminar', views.remove, name='remove'),
]

forms/urls.py
from django.urls import path
from .views import index, login_view, logout_view, register
from products.views import ProductListView

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('registro/', register, name='register'),
]

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('', views.order, name='order'),
    path('direccion', views.address, name='address'),
    path('seleccionar/direccion', views.select_address, name='select_address'),
    path('establecer/direccion/<int:pk>', views.check_address, name='check_address'),
    path('confirmacion', views.confirm, name='confirm'),
    path('cancelar', views.cancel, name='cancel'),
    path('completar', views.complete, name='complete'),
    path('completados', views.OrderListView.as_view(), name='completeds'),
    path('pago', views.payment, name='payment'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <title></title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
    {% if stripe_public_key %}
        <meta name="stripe_public_key" content="{{ stripe_public_key }}">
    {% endif %}

    {% block css %}
    {% endblock %}
</head>
<body>

    {% include 'navbar.html' %}

    <div class="container mt-3">

        {% include 'message.html' %}

        {% block breadcrumb %}
        {% endblock %}

        <div class="row">

            {% block content %}
            {% endblock %}

        </div>
    </div>

</body>
    <script src="https://kit.fontawesome.com/820cf9d6f1.js" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock %}

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="col">
    <h4 class="text-center"> {{ message }} </h4>

    {% include 'products/snippets/search.html' %}

    {% include 'products/snippets/list.html' %}



</div>
{% endblock %}

templates/message.html
{% if messages %}
  {% for message in messages %}
    <div class="alert {% if message.tags == 'success'%}alert-success{%else%}alert-danger{%endif%}">
      <button type="button" class="close" data-dismiss="alert">
        <i class="fas fa-times"></i> <!-- ICON CLOSE -->
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}

templates/navbar.html
{% url 'forms:login' as login %} <!-- Login almacena 'login/' -->
{% url 'forms:register' as register %}
{% url 'forms:logout' as logout %}
{% url 'carts:cart' as cart %}
{% url 'shipping_addresses:shipping_addresses' as shipping_addresses %}
{% url 'orders:completeds' as completeds %}
{% url 'billing_profiles:billing_profiles' as billing_profiles %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'forms:index' %}" class="navbar-brand">Facilito Store</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">

        <ul class="navbar-nav">
            <li class="nav-item {% if request.path == cart %} active {% endif %}">
                <a class="nav-link" href="{{ cart }}">
                    Mi carrito <span class="fas fa-shopping-cart"></span>
                </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item {% if request.path == shipping_addresses %} active {% endif %}">
                <a class="nav-link" href="{{ shipping_addresses }}">
                    Mis direcciones <span class="fas fa-location-arrow"></span>
                </a>
            </li>

            <li class="nav-item {% if request.path == completeds %} active {% endif %}">
                <a class="nav-link" href="{{ completeds }}">
                    Mis pedidos <span class="fas fa-shipping-fast"></span>
                </a>
            </li>

            <li class="nav-item {% if request.path == billing_profiles %} active {% endif %}">
                <a class="nav-link" href="{{ billing_profiles }}">
                    Mis métodos de pago <span class="fab fa-cc-stripe"></span>
                </a>
            </li>
            {% endif %}
        </ul>

        <ul class="nav navbar-nav ml-auto">
            

            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <li class="navbar-item">
                        <a href="/admin" class="nav-link" target="_staff">
                            <i class="fas fa-chess"></i>
                            Dashboard</a>
                    </li>
                {% endif %}
                <li class="navbar-item">
                    <a href="{{ logout }}" class="nav-link">
                        <span class="fas fa-sign-in-alt"></span>
                        Logout</a>
                </li>
            {% else %}
                <li class="navbar-item {% if request.path == login %}active{% endif %}">
                    <a href="{{ login }}" class="nav-link">
                        <span class="fas fa-user"></span>
                        Login</a>
                </li>

                <li class="navbar-item {% if request.path == register %}active{% endif %}">
                    <a href="{{ register }}" class="nav-link">
                        <span class="fas fa-user-plus"></span>
                        Registro</a>
                </li>
            {% endif %}


        </ul>

    </div>

</nav>